### GET request to example server
GET http://127.0.0.1:2323/public-view

### POST get token
POST http://127.0.0.1:2323/get-token
Content-Type: application/json

{
  "email": "djoelplay@gmail.com"
}

> {% client.global.set("token", response.body.data.token); %}

### GET secret to example server
GET http://127.0.0.1:2323/secret-view
Authorization: Bearer {{token}}

